apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: webapp-replica
 labels:
   app: webapp
spec:
 replicas: 3
 selector:
   matchLabels:
     app: webapp
 template:
   metadata:
     labels:
       app: webapp
   spec:
     containers:
     - name: webapp
       image: webapp:1.0.0